version: '3'
services:
  db:
    container_name: vtcmanagerapi-postgresql
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=oauth_demo
    volumes:
      - ./server/common/database/data/sql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
